services:
  liquibase:
    image: liquibase/liquibase:4.29.2
    container_name: liquibase429
    depends_on:
      - postgres
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    command: [ "--logLevel=debug", "--defaultsFile=/liquibase/changelog/local.properties", "status" ]
    networks:
      - app_network

  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: owner
      POSTGRES_PASSWORD: owner123
      POSTGRES_DB: exchange_crypto_local
    ports:
      - "5435:5432"
    volumes:
      - ./liquibase/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8889:8889"   # Prometheus metrics
    depends_on:
      - jaeger
    networks:
      - app_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # Jaeger gRPC (necessário para OTLP)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - app_network


networks:
  app_network:
    driver: bridge