--liquibase formatted sql

--changeset felipe-ascari:create-exchanges-table
CREATE TABLE exchanges (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    varchar(255)   NOT NULL UNIQUE,
    minimum_age             integer        NOT NULL,
    maximum_transfer_amount decimal(15, 2) NOT NULL,
    created_at              timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at              timestamp DEFAULT CURRENT_TIMESTAMP,
    deleted_at              timestamp
);
--rollback DROP TABLE exchanges;

--changeset felipe-ascari:create-users-table
CREATE TABLE users (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        varchar(255) NOT NULL UNIQUE,
    date_of_birth   date         NOT NULL,
    document_number varchar(255) NOT NULL UNIQUE,
    created_at      timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at      timestamp DEFAULT CURRENT_TIMESTAMP,
    deleted_at      timestamp
);
--rollback DROP TABLE users;

--changeset felipe-ascari:create-accounts-table
CREATE TABLE accounts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint         NOT NULL,
    exchange_id bigint         NOT NULL,
    balance     decimal(15, 2) NOT NULL DEFAULT 0.00 CHECK (balance >= 0),
    created_at  timestamp               DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp               DEFAULT CURRENT_TIMESTAMP,
    deleted_at  timestamp,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (exchange_id) REFERENCES exchanges (id) ON DELETE CASCADE,
    UNIQUE (user_id, exchange_id)
);
--rollback DROP TABLE accounts;

--changeset felipe-ascari:create-transaction-type-enum
CREATE TYPE transaction_type AS enum ('DEPOSIT', 'WITHDRAWAL');
--rollback DROP TYPE transaction_type;

--changeset felipe-ascari:create-transactions-table
CREATE TABLE transactions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint           NOT NULL,
    type       transaction_type NOT NULL,
    amount     decimal(15, 2)   NOT NULL CHECK (amount > 0),
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp,
    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE
);
--rollback DROP TABLE transactions;

--changeset felipe-ascari:create-indexes
CREATE INDEX idx_accounts_user_id ON accounts (user_id);
CREATE INDEX idx_accounts_exchange_id ON accounts (exchange_id);
CREATE INDEX idx_transactions_account_id ON transactions (account_id);
CREATE INDEX idx_transactions_created_at ON transactions (created_at);
--rollback DROP INDEX idx_accounts_user_id;
--rollback DROP INDEX idx_accounts_exchange_id;
--rollback DROP INDEX idx_transactions_account_id;
--rollback DROP INDEX idx_transactions_created_at;