// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "exchange-crypto-service-api/internal/app/exchange/domain"

	mock "github.com/stretchr/testify/mock"
)

// ExchangeRepository is an autogenerated mock type for the ExchangeRepository type
type ExchangeRepository struct {
	mock.Mock
}

type ExchangeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ExchangeRepository) EXPECT() *ExchangeRepository_Expecter {
	return &ExchangeRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ExchangeRepository) FindByID(ctx context.Context, id uint) (domain.Exchange, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Exchange
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (domain.Exchange, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) domain.Exchange); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Exchange)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExchangeRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ExchangeRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *ExchangeRepository_Expecter) FindByID(ctx interface{}, id interface{}) *ExchangeRepository_FindByID_Call {
	return &ExchangeRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *ExchangeRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *ExchangeRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *ExchangeRepository_FindByID_Call) Return(_a0 domain.Exchange, _a1 error) *ExchangeRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExchangeRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (domain.Exchange, error)) *ExchangeRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewExchangeRepository creates a new instance of ExchangeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExchangeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExchangeRepository {
	mock := &ExchangeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
