// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "exchange-crypto-service-api/internal/app/account/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, account
func (_m *Repository) Create(ctx context.Context, account domain.Account) (domain.Account, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account) (domain.Account, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account) domain.Account); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Get(0).(domain.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Account) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account domain.Account
func (_e *Repository_Expecter) Create(ctx interface{}, account interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, account domain.Account)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Account))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 domain.Account, _a1 error) *Repository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(context.Context, domain.Account) (domain.Account, error)) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
